### PR TITLE
wopiserver: update to v8.0.2, wopibridge to v4.4.0

### PR DESCRIPTION
**Pull request by dagl**
### Contributing a Chart / update to an existing Chart

- [x] Run `helm lint` on the chart dir.
- [x] (Update) Bump the `Chart.yaml` version before merging, to release it as a new version.
- [ ] (Update) If the PR includes new configurable parameters in the chart's `values.yaml`. Add documentation in the appropiate README.

### CODE REVIEW

**Comment by SamuAlfageme** [comment]
@dagl the wopibridge component was dropped and its functionality embedded on the wopiserver itself a few months ago. In order to bump the WS version you could pick up the work started by @glpatcern on https://github.com/cs3org/charts/pull/28

**Comment by dagl** [comment]
> @dagl the wopibridge component was dropped and its functionality embedded on the wopiserver itself a few months ago. In order to bump the WS version you could pick up the work started by @glpatcern on #28

What happened to that PR, is @glpatcern no longer working on it? I have little to no idea about how wopiserver works and communicates with Reva so I don't think I can pick it up.

**Comment by glpatcern** [comment]
> > @dagl the wopibridge component was dropped and its functionality embedded on the wopiserver itself a few months ago. In order to bump the WS version you could pick up the work started by @glpatcern on #28
> 
> What happened to that PR, is @glpatcern no longer working on it? I have little to no idea about how wopiserver works and communicates with Reva so I don't think I can pick it up.

@dagl I've been taken by other tasks but clearly it's a work to be finished. Simply it requires some fixes at the helm level (which I know not much yet). As a matter of fact, you don't need to know much about how wopiserver communicates with Reva, given that the interaction basically remained the same: if you see the PR it's all about cleaning up the wopibridge. Therefore if you can have a look and you have some helm knowledge I think you can sort things out.

At the same time, I think this PR should be closed.

**Comment by glpatcern** [comment]
Closing this so we continue the discussion on #28.

**Pull request closed without merging**
