### PR TITLE
update wopi server to v10.1.0

### PR DESCRIPTION
**Pull request by wkloucek**
### Contributing a Chart / update to an existing Chart

- [x] Run `helm lint` on the chart dir.
- [x] (Update) Bump the `Chart.yaml` version before merging, to release it as a new version.
- [x] (Update) Replace the `annotations` on the `Chart.yaml` with:
  - `artifacthub.io/changes` - the changes introduced on the PR [with the appropiate format](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations).
  - `artifacthub.io/images` - the updated tag on the `cs3org/revad` image.
- [ ] (Update) If the PR includes new configurable parameters in the chart's `values.yaml`. Add documentation in the appropiate README.

### CODE REVIEW

**Comment by wkloucek** [comment]
@glpatcern looks like the CI is failing because the WOPI server image does not exist:
```
Warning  Failed     8m34s (x4 over 10m)     kubelet, chart-testing-control-plane  Failed to pull image "cs3org/wopiserver:v10.0.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/cs3org/wopiserver:v10.0.2": failed to resolve reference "docker.io/cs3org/wopiserver:v10.0.2": docker.io/cs3org/wopiserver:v10.0.2: not found
```

Could you please have a look? I assumed it exists, because you thankfully did a release of the WOPI server: https://github.com/cs3org/wopiserver/releases/tag/v10.0.2

**Comment by glpatcern** [comment]
@wkloucek I have tagged that release on a feature branch for testing, maybe that's why you can't find the image as it was not built out of the main branch. I'll make that feature depend on a configuration parameter, so that we can merge it and create a regular tag.

**Comment by wkloucek** [comment]
> @wkloucek I have tagged that release on a feature branch for testing, maybe that's why you can't find the image as it was not built out of the main branch. I'll make that feature depend on a configuration parameter, so that we can merge it and create a regular tag.

`cs3org/wopiserver:v10.0.2-amd64` and `cs3org/wopiserver:v10.0.2-arm64` are already available.

To be honest, from the tag alone I would not have guessed that this is no release but only for testing. On https://github.com/cs3org/wopiserver/tags `v10.0.1` and `v10.0.2` look exactly the same. According to Semver `v10.0.2` also is a patch version of `v10.0.1` and not a pre-release.

**Comment by glpatcern** [comment]
Indeed it's only the `xrootd` flavour that for some reasons did not build, otherwise the tag was meant to be usable as "usual", though including this testing feature.

Yet, this is a patch release (3rd number), not a real release with a changelog - that would be `v10.1.0`. We've been deploying at times such patch releases but they have never been blessed as releases.

**Comment by wkloucek** [comment]
> Indeed it's only the `xrootd` flavour that for some reasons did not build, otherwise the tag was meant to be usable as "usual", though including this testing feature.
> 
> Yet, this is a patch release (3rd number), not a real release with a changelog - that would be `v10.1.0`. We've been deploying at times such patch releases but they have never been blessed as releases.

ahh ok, then I may have misunderstood you. The tag `v10.0.2` will stay on this branch / commit and also they docker images stay available like they currenlty are?

**Comment by glpatcern** [comment]
I have deleted this tag, see https://github.com/cs3org/wopiserver/pull/126.
And I have properly tagged a `v10.1.0` release.

**Comment by wkloucek** [comment]
> I have deleted this tag, see [cs3org/wopiserver#126](https://github.com/cs3org/wopiserver/pull/126). And I have properly tagged a `v10.1.0` release.

Thanks! I updated this PR, to use v10.1.0, but seems that the manifest publish step was skipped because of an prior error: https://github.com/cs3org/wopiserver/actions/runs/5462921527/jobs/9943271709 
Could you please have a look? ( I can't see the logs)

**Comment by glpatcern** [comment]
It's not a previous error, it's still the same issue (indeed, tagging a branch or `master` doesn't matter). I don't understand why the build fails with the xroot flavour (but not with the others), and then the images are not properly published.

**Comment by glpatcern** [comment]
For the record, I've blindly tried to clean up / restart the GitHub runners, to no avail. Something is currently broken in the wopiserver CI and we don't seem to be able to get a successful build, despite the build works on a local run.

**Comment by glpatcern** [comment]
Finally sorted out the build, due to an issue with the xrootd "flavour". I see you are already rerunning the CI here ;-)

**Comment by wkloucek** [comment]
@glpatcern Thanks for fixing the 10.1.0 image release on Dockerhub!

Unfortunately this CI fails now, because the WOPI server expects a up and running CS3api. Should we add REVA or oCIS to the WOPI server CI in order to make it green again?

**Comment by glpatcern** [comment]
> @glpatcern Thanks for fixing the 10.1.0 image release on Dockerhub!
> 
> Unfortunately this CI fails now, because the WOPI server expects a up and running CS3api.

You're welcome, and yes, now the CI would need to spin up a Reva gateway for the WOPI server to start successfully. Would you be able to extend the script to cover that? Otherwise, the test step is to be suppressed (which is a pity...).

**Comment by wkloucek** [comment]
I'm currently quite booked, so that I didn't come to look into spinning up a Reva gateway in CI.

**Pull request closed without merging**
