### PR TITLE
Update revad version and entrypoint

### PR DESCRIPTION
**Pull request by SamuAlfageme**
Draft until https://github.com/cs3org/reva/pull/1797 is merged and `v1.9.0` is released

### Contributing a Chart / update to an existing Chart

- [x] Run `helm lint` on the chart dir.
- [x] (Update) Bump the `Chart.yaml` version before merging, to release it as a new version.
- [ ] ~~(Update) If the PR includes new configurable parameters in the chart's `values.yaml`. Add documentation in the appropiate README.~~

### CODE REVIEW

**Review by Daniel-WWU-IT — COMMENTED** [review]
Looks fine to me. Not sure why the checks are failing...

**Comment by Daniel-WWU-IT** [comment]
@SamuAlfageme Do you have an idea why the check is failing? Otherwise, I'd just merge this PR, as the charts are really lacking behind by now...

**Comment by SamuAlfageme** [comment]
@Daniel-WWU-IT it appears CI install step is failing due to some unrelated issues (most likely on [helm/kind-action](https://github.com/helm/kind-action)). Agreed, I'll merge it as is and fix that later.

**Comment by SamuAlfageme** [comment]
Here's the issue just for reference: https://github.com/helm/kind-action/issues/42

**Pull request merged**
